### PR TITLE
memory footprint reductions

### PR DESCRIPTION
**Pull request by MarvinT**

### CODE REVIEW

**Comment by neuromusic** [comment]
I don't see any red flags

**Comment by MarvinT** [comment]
On lintu:
On a 1 hour 16 channel recording:
Before:
peak memory usage: 17.188812 GB
time: 0:06:10.007549
After:
peak memory usage: 5.817806 GB
time: 0:05:00.122127

**Comment by neuromusic** [comment]
awesome

**Comment by MarvinT** [comment]
on justin's 32 channel recording:
peak memory usage: 23.637543 GB
time: 0:30:07.023822

also, average memory usage is much lower than peak as well because I del some unused variables

**Pull request merged**
