### PR TITLE
added realignment option, addresses issue #6

### PR DESCRIPTION
**Pull request by neuromusic**
Current options include spline (default) and none

### CODE REVIEW

**Comment by MarvinT** [comment]
Since you guys seem to get a kick out of overzealous code reviews, I'll be a bit more critical:

The whole point is to reduce code duplication. `realign(r,chans,fs,method):` should perform all the tasks that `no_realign` and 'spline_realign` do the same. i.e. prepopulating rec or possibly trimming the data although that might be more different that it seems.

There are lots of extra unnecessary lines and code. If you don't use a variable, it should be removed before you merge it into the master branch. In this case, in the `no_realign` function, I don't think you use:
* `starts`
* `stops`
* `lengths`
* `t_new`
after initializing them

I feel like defining `shape` on l180 should be done inline on l183. I feel like factoring it out doesn't increase readability of the code.

I feel like l193 and l194 should be combined. There's no reason to make an intermediate variable here.

You have 2 white lines after the definition of `realign` on l207. While strictly speaking this matches [Google's python style guide](https://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Blank_Lines#Blank_Lines) of having 2 blank lines between top level definitions, it doesn't follow the rule that takes precedent which is being consistent with surrounding code which only uses 1 blank line.

Similarly, you shouldn't have blank lines on l147, l170, and l199

You shouldn't use 1 letter argument names even if you have adequate documentation, but especially since we don't document our functions.

Commented out code shouldn't be in the master branch.

There are also some unnecessary comments such as `# print import_list` and ~~`# Realignment methods:`~~. From [Google](https://google-styleguide.googlecode.com/svn/trunk/pyguide.html?showone=Comments#Comments) again 
>[Except in tricky or complicated parts], never describe the code. Assume the person reading the code knows Python (though not what you're trying to do) better than you do.

Feel free to pick and choose which critiques to take, and besides these it looks great :stuck_out_tongue_winking_eye:

**Comment by MarvinT** [comment]
We should also improve the documentation for the arguments.

For example, each argument should tell whether it's required, what the default values are and what possible values it will accept.
Also, possibly examples.

**Comment by MarvinT** [comment]
I'm going to rebase to 79c32c4456ea8c4ed5860a3cd0e93cab5d375dd4 make sure to pull in a sec

**Comment by MarvinT** [comment]
I would still like to see a couple of things before merging the pull request:
- [ ] reduce code duplication
- [ ] better documentation for the arguments
- [ ] [merge commits and rebase](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

If you'd like me to demonstrate what I mean by doing any of these let me know.

Also, you should finish this and we should merge this pull request before pull request #9 so that you don't have to deal with conflicts. That's a lesson for another time :smile:

**Comment by theilmbh** [comment]
I think I got the rebase done correctly.  Then I changed it so that "realign" precomputes start and stop and also begins to populate rec.  Now all the specific realignment methods have to do is return a realigned data vector which gets added to the rec dictionary and returned.  How does it look?

**Comment by theilmbh** [comment]
Welp think I messed something up

**Pull request merged**
