### PR TITLE
added Buzsaki32 and A4x4 probes

### PR DESCRIPTION
**Pull request by MarvinT**

### CODE REVIEW

**Comment by zekearneodo** [comment]
looks good to me

**Comment by neuromusic** [comment]
aren't these assigning ALL channels to each channel group?

e.g.

``` Python
channel_groups[i] = {'channels': s.values()}
```

**Comment by neuromusic** [comment]
shouldn't it be something like...

```
    elif probe=='Buzsaki32':
        channel_groups = {}
        for i in range(4):
            channel_groups[i] = {'channels': [n+i*8+1 for n in range(8)]}
            channel_groups[i]['geometry'] = {
                s[5 + i*8]: (0 + 200 * i, 0),
                s[4 + i*8]: (-8.5 + 200 * i, 20),
                s[6 + i*8]: (8.5 + 200 * i, 40),
                s[3 + i*8]: (-12.5 + 200 * i, 60),
                s[7 + i*8]: (12.5 + 200 * i, 80),
                s[2 + i*8]: (-16.5 + 200 * i, 100),
                s[8 + i*8]: (16.5 + 200 * i, 120),
                s[1 + i*8]: (-20.5 + 200 * i, 140),
            }
```

**Comment by neuromusic** [comment]
oops. I mean

```
    elif probe=='Buzsaki32':
        channel_groups = {}
        for i in range(4):
            channel_groups[i] = {'channels': [s[n+i*8+1] for n in range(8)]}
            channel_groups[i]['geometry'] = {
                s[5 + i*8]: (0 + 200 * i, 0),
                s[4 + i*8]: (-8.5 + 200 * i, 20),
                s[6 + i*8]: (8.5 + 200 * i, 40),
                s[3 + i*8]: (-12.5 + 200 * i, 60),
                s[7 + i*8]: (12.5 + 200 * i, 80),
                s[2 + i*8]: (-16.5 + 200 * i, 100),
                s[8 + i*8]: (16.5 + 200 * i, 120),
                s[1 + i*8]: (-20.5 + 200 * i, 140),
            }
```

or perhaps more generally

```
    elif probe=='Buzsaki32':
        channel_groups = {}
        for i in range(4):
            channel_groups[i]['geometry'] = {
                s[5 + i*8]: (0 + 200 * i, 0),
                s[4 + i*8]: (-8.5 + 200 * i, 20),
                s[6 + i*8]: (8.5 + 200 * i, 40),
                s[3 + i*8]: (-12.5 + 200 * i, 60),
                s[7 + i*8]: (12.5 + 200 * i, 80),
                s[2 + i*8]: (-16.5 + 200 * i, 100),
                s[8 + i*8]: (16.5 + 200 * i, 120),
                s[1 + i*8]: (-20.5 + 200 * i, 140),
            }
            channel_groups[i] = channel_groups[i]['geometry'].keys()
```

**Comment by MarvinT** [comment]
yup!

**Comment by neuromusic** [comment]
gah!

```
    elif probe=='Buzsaki32':
        channel_groups = {}
        for i in range(4):
            channel_groups[i] = {}
            channel_groups[i]['geometry'] = {
                s[5 + i*8]: (0 + 200 * i, 0),
                s[4 + i*8]: (-8.5 + 200 * i, 20),
                s[6 + i*8]: (8.5 + 200 * i, 40),
                s[3 + i*8]: (-12.5 + 200 * i, 60),
                s[7 + i*8]: (12.5 + 200 * i, 80),
                s[2 + i*8]: (-16.5 + 200 * i, 100),
                s[8 + i*8]: (16.5 + 200 * i, 120),
                s[1 + i*8]: (-20.5 + 200 * i, 140),
            }
            channel_groups[i]['channels'] = channel_groups[i]['geometry'].keys()
```

**Pull request merged**
