### PR TITLE
make_kwd doesn't properly default when sampling frequency isn't supplied

### PR DESCRIPTION
**Pull request by MarvinT**

### CODE REVIEW

**Comment by neuromusic** [comment]
AA+++++ great coder. would review again

**Comment by neuromusic** [comment]
changed my mind. on the two assertions, can you clarify that they are checking across recordings and channels?

**Comment by neuromusic** [comment]
that is, in the error string that each assertion throws?

**Comment by MarvinT** [comment]
better?

**Comment by neuromusic** [comment]
fantastic. approved.

**Pull request merged**
