### PR TITLE
fixing rig configuration maps for burung

### PR DESCRIPTION
**Pull request by MarvinT**
fixes issue #27

### CODE REVIEW

**Comment by neuromusic** [comment]
imho it shouldn't be possible to pass in a "rig" argument that doesn't exist but at least this fixes the problem

**Comment by neuromusic** [comment]
from chatting with @neurologic, the "no-adapter" config was a mistake that does not need to be supported for any backwards compatibility

**Comment by MarvinT** [comment]
Well apply adapter does use it. You would argue for it only existing as a temporary variable?

**Comment by gentnerlab-user** [comment]
Yes

**Comment by MarvinT** [comment]
How's this?

**Comment by neuromusic** [comment]
I dig it

**Pull request merged**
